# The auto-assign bot will randomly select a reviewer from this list of usernames.
groups:
  - name: dependabot-reviewers
    reviewers: 1
    usernames:
      - robotrapta
      - tyler-romero
      - sunildkumar
      - tomfaulhaber
      - roxanne-o
      - timmarkhuff
      - brandon-groundlight
      - f-wright
      - CoreyEWood
      - honeytung
