site_name: Groundlight
site_url: https://groundlight.ai
nav:
  - Getting Started:
      - Introduction: index.md
      - Managing Confidence and Latency: managing-confidence.md
  - Building Applications:
      - Working with Detectors: working-with-detectors.md
      - Handling Errors: handling-errors.md
      - Running on the Edge: edge.md
      - Installation FAQs: installation-faqs.md
  # - Examples:
  #     - Cool Thing 1: cool-thing-1.md
  #     - Cool Thing 2: cool-thing-2.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: purple
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  favicon: img/favicon.ico
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - mdx_include:
      base_path: docs
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
