name: auto-format
on: pull_request
jobs:
  format:
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.10"
      POETRY_VERSION: "1.4.0"
    steps:
      - name: get code
        uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: install poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
      - name: install linter dependencies
        run: |
          make install-lint
      - name: run formatter
        run: |
          make format
      - name: check for modified files
        id: git-check
        run: |
          git status
          echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: push changes (if needed)
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Auto-format Bot'
          git config --global user.email 'autoformatbot@groundlight.ai'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automatically reformatting code"
          git push
