# Run our linter on every push to the repository.
name: lint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.10"
      POETRY_VERSION: "1.4.0"
    steps:
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: install poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
      - name: get code
        uses: actions/checkout@v3
      - name: install linter dependencies
        run: |
          make install-lint
      - name: lint
        run: |
          make lint
