name: publish-docs
on:
  push:
    paths:
      # Only run this workflow if there are changes in any of these files.
      - .github/workflows/**
      - docs/**
    branches:
      - main
defaults:
  run:
    working-directory: docs

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Build website
        run: npm run build
      - name: Deploy website
        # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
        uses: peaceiris/actions-gh-pages@v3
        # Only run this on pushes to the `docs`
        if: github.ref == 'refs/heads/docs'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          #TODO: setup a staging directory when doing a PR
          #destination_dir: staging
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
